### ISSUE TITLE
docker tag related issues when running the network.sh script from latest MAIN branch

### ISSUE THREAD

**Issue by shoebsd31** [hyperledger/fabric-samples#496] opened 2021-09-28 05:40 UTC
Hi, 

When I take the latest version from git respository (MAIN branch) and try to run the network, I get the following error : 

**docker: Error response from daemon: manifest for hyperledger/fabric-tools:latest not found: manifest unknown: manifest unknown.**

and warning : 
**Local fabric-ca binaries and docker images are out of sync. This may cause problems.**

![image](https://user-images.githubusercontent.com/5415085/135029415-8e9a56fd-68d9-43a3-b2e3-db5496621fc8.png)

Is there something missing in the documentation ? or do I need to change something in the config files ?

It runs when I remove the **latest** tag and put some version for example hyperledger/fabric-tools:2.3.3

**Comment by achernetsov** [comment] 2021-09-30 18:36
looks like problem is in installation script. It supposed to download version of specific version and tag it as latest locally. It do it for other images, but not tools.

```
hyperledger/fabric-ca        1.5       4ea287b75c63   2 weeks ago   69.7MB
hyperledger/fabric-ca        1.5.2     4ea287b75c63   2 weeks ago   69.7MB
hyperledger/fabric-ca        latest    4ea287b75c63   2 weeks ago   69.7MB
hyperledger/fabric-tools     2.3.3     98fa0bfb0fd2   3 weeks ago   445MB
hyperledger/fabric-peer      2.3       a491b5ab42f6   3 weeks ago   53.3MB
hyperledger/fabric-peer      2.3.3     a491b5ab42f6   3 weeks ago   53.3MB
hyperledger/fabric-peer      latest    a491b5ab42f6   3 weeks ago   53.3MB
hyperledger/fabric-orderer   2.3       9e1952b8840d   3 weeks ago   35.4MB
hyperledger/fabric-orderer   2.3.3     9e1952b8840d   3 weeks ago   35.4MB
hyperledger/fabric-orderer   latest    9e1952b8840d   3 weeks ago   35.4MB
hyperledger/fabric-baseos    2.3       b35a8ef578c0   3 weeks ago   6.87MB
hyperledger/fabric-baseos    2.3.3     b35a8ef578c0   3 weeks ago   6.87MB
hyperledger/fabric-baseos    latest    b35a8ef578c0   3 weeks ago   6.87MB
```

**Comment by lehors** [comment] 2022-02-16 11:03
I'm not sure how you ended up in this situation but I cannot reproduce this. I just tried it again and it worked:

```
===> List out hyperledger docker images
hyperledger/fabric-tools     2.4       eb40f70b1174   2 weeks ago    473MB
hyperledger/fabric-tools     2.4.2     eb40f70b1174   2 weeks ago    473MB
hyperledger/fabric-tools     latest    eb40f70b1174   2 weeks ago    473MB
hyperledger/fabric-peer      2.4       43b970f84604   2 weeks ago    62.3MB
hyperledger/fabric-peer      2.4.2     43b970f84604   2 weeks ago    62.3MB
hyperledger/fabric-peer      latest    43b970f84604   2 weeks ago    62.3MB
hyperledger/fabric-orderer   2.4       5edf6bdb4489   2 weeks ago    37.3MB
hyperledger/fabric-orderer   2.4.2     5edf6bdb4489   2 weeks ago    37.3MB
hyperledger/fabric-orderer   latest    5edf6bdb4489   2 weeks ago    37.3MB
hyperledger/fabric-ccenv     2.4       e377a02242aa   2 weeks ago    517MB
hyperledger/fabric-ccenv     2.4.2     e377a02242aa   2 weeks ago    517MB
hyperledger/fabric-ccenv     latest    e377a02242aa   2 weeks ago    517MB
hyperledger/fabric-baseos    2.4       4cfe0148d657   2 weeks ago    6.94MB
hyperledger/fabric-baseos    2.4.2     4cfe0148d657   2 weeks ago    6.94MB
hyperledger/fabric-baseos    latest    4cfe0148d657   2 weeks ago    6.94MB
hyperledger/fabric-ca        1.5       4ea287b75c63   5 months ago   69.8MB
hyperledger/fabric-ca        1.5.2     4ea287b75c63   5 months ago   69.8MB
hyperledger/fabric-ca        latest    4ea287b75c63   5 months ago   69.8MB
```
So, I'm closing this issue (which would be against fabric rather than fabric-samples anyway).

**Closed by lehors** 2022-02-16 11:03 UTC

**Comment by nikhil550** [comment] 2022-02-18 02:30
This may have been a Mac M1 issue. Pulling from an M1 mac produces a similar error if I remember.
