### ISSUE TITLE
just microfab  error while starting container

### ISSUE THREAD

**Issue by ggichuru** [hyperledger/fabric-samples#1002] opened 2023-03-13 13:58 UTC
I am trying to run the` just microfab` command but i am getting this error: 

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at MicrofabProcessor.<anonymous> (/home/ggichuru/.nvm/versions/node/v16.18.0/lib/node_modules/@hyperledger-labs/weft/src/microfab.ts:43:29)
    at Generator.next (<anonymous>)
    at /home/ggichuru/.nvm/versions/node/v16.18.0/lib/node_modules/@hyperledger-labs/weft/lib/microfab.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ggichuru/.nvm/versions/node/v16.18.0/lib/node_modules/@hyperledger-labs/weft/lib/microfab.js:27:12)
    at MicrofabProcessor.processFile (/home/ggichuru/.nvm/versions/node/v16.18.0/lib/node_modules/@hyperledger-labs/weft/lib/microfab.js:47:16)
    at /home/ggichuru/.nvm/versions/node/v16.18.0/lib/node_modules/@hyperledger-labs/weft/src/cli.ts:530:37
    at Generator.next (<anonymous>)
    at /home/ggichuru/.nvm/versions/node/v16.18.0/lib/node_modules/@hyperledger-labs/weft/lib/cli.js:32:71
error: Recipe `microfab` failed with exit code 1

```

**NOTE**: microfab was runnig before. 

i am using an Arch Linux distro

**Comment by bestbeforetoday** [comment] 2024-12-03 11:33
I ran the full-stack-asset-transfer-guide sample (chaincode and application dev sections) successfully last week using the current content of the _main_ branch. This involved starting microfab with `just microfab`. Since I can't reproduce this issue, I'll close it. Please comment if you continue to see a problem.

**Closed by bestbeforetoday** 2024-12-03 11:33 UTC
