### ISSUE TITLE
Java chaincode: undefined contract called

### ISSUE THREAD

**Issue by tassiLuca** [hyperledger/fabric-samples#1077] opened 2023-07-21 10:25 UTC
**Problem**: attempting to reproduce the [deployment tutorial](https://hyperledger-fabric.readthedocs.io/en/latest/deploy_chaincode.html) using the java version of the chaincode asset-transfer-basic (see [here](https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic/chaincode-java)) leads to `Undefined contract called` when trying to invoke a transaction. Following the same approach for the Go chaincode version everything works as expected.

Here the list of commands:
```bash
./network.sh up createChannel       
```
```bash
./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-java -ccl java -c mychannel
```

```bash
peer chaincode invoke -o localhost:7050 --ordererTLSHostnameOverride orderer.example.com --tls --cafile "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem" -C mychannel -n basic --peerAddresses localhost:7051 --tlsRootCertFiles "${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt" --peerAddresses localhost:9051 --tlsRootCertFiles "${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt" -c '{"function":"InitLedger","Args":[]}'
```

The resulting **error** is the following:
```
Error: endorsement failure during invoke. response: status:500 message:"Undefined contract called"
```

Checking the container's logs a `org.hyperledger.fabric.contract.ContractRuntimeException:` exception is thrown:
```
2023-07-21 12:17:39 Thread[fabric-txinvoke:3,5,main] 10:17:39:936 INFO    org.hyperledger.fabric.contract.ContractRouter processRequest                    Got invoke routing request
2023-07-21 12:17:39 Thread[fabric-txinvoke:3,5,main] 10:17:39:941 INFO    org.hyperledger.fabric.contract.ContractRouter processRequest                    Got the invoke request for:InitLedger []
2023-07-21 12:17:39 Thread[fabric-txinvoke:3,5,main] 10:17:39:942 SEVERE  org.hyperledger.fabric.Logger error                                              Undefined contract calledorg.hyperledger.fabric.contract.ContractRuntimeException: Undefined contract called
2023-07-21 12:17:39     at org.hyperledger.fabric.contract.routing.impl.RoutingRegistryImpl.getContract(RoutingRegistryImpl.java:119)
2023-07-21 12:17:39     at org.hyperledger.fabric.contract.ContractRouter.getRouting(ContractRouter.java:154)
2023-07-21 12:17:39     at org.hyperledger.fabric.contract.ContractRouter.processRequest(ContractRouter.java:114)
2023-07-21 12:17:39     at org.hyperledger.fabric.contract.ContractRouter.invoke(ContractRouter.java:134)
2023-07-21 12:17:39     at org.hyperledger.fabric.shim.impl.ChaincodeInvocationTask.call(ChaincodeInvocationTask.java:106)
2023-07-21 12:17:39     at org.hyperledger.fabric.shim.impl.InvocationTaskManager.lambda$newTask$17(InvocationTaskManager.java:265)
2023-07-21 12:17:39     at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
2023-07-21 12:17:39     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-07-21 12:17:39     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-07-21 12:17:39     at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by gqqnbig** [comment] 2023-09-23 08:14
Possible duplicate of #559 

You must compile chaincode with jdk 11.

**Comment by giovaz94** [comment] 2023-09-26 14:47
Hi, I think this aspect needs to be reported somewhere in the official documentation and not only in [this](https://github.com/hyperledger/fabric-chaincode-java/blob/main/COMPATIBILITY.md) readme.

**Closed** 2023-09-29 08:02 UTC
